### ISSUE TITLE
Data lake solution - user's permission issue

### ISSUE THREAD

**Issue by harikrishna1210** [awslabs/aws-data-lake-solution#1]
Hi, 

Reference: http://docs.aws.amazon.com/solutions/latest/data-lake-solution/deployment.html

I created a "Data lake" from the cloud formation template in Oregon region and all seems to have completed successfully from a cloud formation perspective. As the admin I able to login into Data lake UI but not able to create new package, it's throwing below error:

Service Error
**{"error":{"message":"User is not authorized to perform the requested action."}}**
Also unable to get users and settings information under Administration tab:
Service error
**An unexpected error has occurred while retrieving users.**
Service error
**An unexpected error has occurred while retrieving settings.**

Any suggestions to resolve this issue will be very helpful to us

Thanks,
Hari.

**Comment by shsenior** [comment]
Fixed issue by adding header capitalization checks for inbound microservice proxy requests from API.
