### ISSUE TITLE
Fails to deploy, bucket interpolation bug

### ISSUE THREAD

**Issue by john-aws** [awslabs/aws-data-lake-solution#11]
The data lake solution fails to deploy, with the following CloudFormation error:

    Template bucket referenced by https://s3.amazonaws.com/mybucket-us-east-1/data-lake/latest/data-lake-storage.yaml does not exist.

The deploy instructions tell the user to set DEPLOY_BUCKET to the desired S3 bucket that will host deployment assets, to then build the deployment assets, and finally copy them to the aforementioned bucket.

The build-s3-dist.sh script replaces BUCKET_NAME in the deployment YAML file with the value that the user supplied in DEPLOY_BUCKET. However, the nested stacks (e.g. DataLakeStorageStack) use the following:

    !Join ["-", [!FindInMap ["SourceCode", "General", "S3Bucket"], Ref: "AWS::Region"]]

This results in CloudFormation stack creation failure because CloudFormation is looking for the YAML file in a bucket with the region suffix:

    s3.amazonaws.com/mybucket-us-east-1/data-lake/latest/data-lake-storage.yaml

when, in fact, the YAML file is in a bucket without the region suffix:

    s3.amazonaws.com/mybucket/data-lake/latest/data-lake-storage.yaml

**Comment by hvital** [comment]
The [version 2.0 was published](https://aws.amazon.com/about-aws/whats-new/2018/07/the-data-lake-solution-now-transforms-and-analyzes-data/) and [README.md](https://github.com/awslabs/aws-data-lake-solution/blob/master/README.md) was reviewed to add more details about how source-**bucket-base-name** build parameter works. 

This structure of appending the region code was created to help [Automated Deployment](https://docs.aws.amazon.com/solutions/latest/data-lake-solution/deployment.html). The S3 bucket where the lambda .zip packages are stored must reside in the same AWS Region that you're creating the Lambda function in (more info [here](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-lambda-function-code.html#cfn-lambda-function-code-s3bucket)). The solution then keeps a copy of all assets in every supported region and when you run the template, it will search for dependencies in the same region.
