### ISSUE TITLE
Unit test script removed, but still mentioned in readme

### ISSUE THREAD

**Issue by justinclayton** [awslabs/aws-data-lake-solution#19]
In the README, [step 4 under the Getting Started section](https://github.com/awslabs/aws-data-lake-solution#04-run-the-data-lake-solution-unit-tests) instructs the user to run `./run-unit-tests.sh` from the `deployment` directory. However, that script was removed in [a14317d](https://github.com/awslabs/aws-data-lake-solution/commit/a14317d53b2a1955dd9d2e18145792985f358a44#diff-e669ab8bd1d0eb2175e0e8ab621f8209).

**Comment by hvital** [comment]
Thanks for the feedback! Will check this for the next release.

**Comment by shsenior** [comment]
Resolved in v2.1.0 update.
