### ISSUE TITLE
Issue creating package

### ISSUE THREAD

**Issue by coichedid** [awslabs/aws-data-lake-solution#20]
Hello guys,

After deploy my datalake with CloudFormation template, I logged in DataLake Console and tried to create a new package.
I've supplied required parameters and everything apparently worked fine, but behind the scenes I got two 502 errors. Console couldn't find crawler metadata and tables. 
As I could see, nothing was created in AWS Glue and even if I browse to package edition screen and try to upload a file or even a manifest, nothing happens and I'm not able to save my package. 

I really don't know where I can see any glue. I searched every Cloud Watch log entry and found nothing. 

Could you help me?

Regards,
Clovis Chedid

**Comment by hvital** [comment]
Hi Clovis,

Did you upload a dataset to this package? Or just created the package and then access it (from search result page or directly link)?

**Comment by hvital** [comment]
Thanks for your help. 
Will include the fix for this in the next release.

**Comment by shsenior** [comment]
Resolved in v2.1.0 update.
