### ISSUE TITLE
Hyphen character in package name is causing issues.

### ISSUE THREAD

**Issue by iacechua** [awslabs/aws-data-lake-solution#24]
A hyphen in the start of the package name seems to be causing issues. Are there any workarounds?

user$ datalake get-package-crawler --package-id '-Ugxxxxxx'
error: unknown option `-g'

user$ datalake list-package-tables --package-id '-Ugxxxxxx'
error: unknown option `-g'

We have tried single quotes, double quotes, and prepending with a \ character.

Sample of working queries:

$ datalake get-package-crawler --package-id "a6vxxxxxx"
{"name":"delighted a6vxxxxxx","status":"READY","lastRun":"SUCCEEDED"}

Background of the issue: The package should have been deleted but is still showing up on the console.

**Comment by beomseoklee** [comment]
Thanks for your input, and I'm sorry for the late response. We will consider this one in the next release.

**Comment by georgebearden** [comment]
The shortid character set has been updated to remove ‘-‘ in the latest commit. This should resolve the issue.
