### ISSUE TITLE
Installing Data Lake CLI on Windows

### ISSUE THREAD

**Issue by jlopezvi** [awslabs/aws-data-lake-solution#25]
I have used the CloudFormation template to generate the aws-data-lake-solution in my AWS account.

I would like to import several files / folders *simultaneously* into a package in the Data Lake Console (cloudfront) from my computer. I cannot do this using the Console and I have thought of the CLI. All the computers in our network are Windows. There are no instructions as to how to install the CLI for Windows. Any help ?

**Comment by hayesry** [comment]
Hi @jlopezvi, thanks for reaching out! I've attached a link below to the official AWS documentation for installing the CLI on Windows.

Link: (https://docs.aws.amazon.com/cli/latest/userguide/install-windows.html)

**Comment by jlopezvi** [comment]
I am referring to the DATA LAKE CLI and not the AWS CLI.
Are these two the same?
http://docs.awssolutionsbuilder.com/data-lake/cli/cli-getting-started/
