### ISSUE TITLE
data-lake-deploy.template does not exist in "dist" folder after build

### ISSUE THREAD

**Issue by shaoliang-jia-dragon** [awslabs/aws-data-lake-solution#26]
Hi,

After this step "Build the data lake solution for deployment", I didn't find "data-lake-deploy.template" or "data-lake-deploy-federated.template" in the dist folder.

I tried to copy the "data-lake-deploy.template" and "data-lake-deploy-federated.template" to "dist" folder and then upload to s3 bucket. However, I got "TemplateURL must be an Amazon S3 URL" error when running "Deploy the data lake solution" using Cloudformation.

Here are my environment variables:
    export AWS_REGION=us-east-1
    export VERSION_CODE=v2.0.0
    export DEPLOY_BUCKET=jslake

**Comment by timcleaver** [comment]
Not sure if it still matters, but lines 54-57 of deployment/build-s3-dist.sh refer to data-lake-deploy.yaml and data-lake-federated.yaml to be copied into dist/. These files should actually be data-lake-deploy.template and data-lake-federated.template. I have attached a patch to fix this. It also adds set -e, set -u and set -o pipefail bash options which should cause the script to fail if any subcommands fail. There are a number of other smaller changes to handle other failures that set -e highlighted. 
[build-s3-dist.sh.txt](https://github.com/awslabs/aws-data-lake-solution/files/3016129/build-s3-dist.sh.txt)

**Comment by shaoliang-jia-dragon** [comment]
Thanks. Will verify later.

**Comment by sardbaba** [comment]
@shaoliang-jia-dragon  please see https://github.com/awslabs/aws-data-lake-solution/pull/21
I think you can close this issue.

**Comment by shaoliang-jia-dragon** [comment]
Which issue is it related to?

**Comment by sardbaba** [comment]
Yes sorry, your issue has two parts:

- the title of this issue refers to the same issue resolved here https://github.com/awslabs/aws-data-lake-solution/pull/21
- "TemplateURL must be an Amazon S3 URL" seems another kind of problem.
Did you copy the code with:
`aws s3 cp ./dist s3://$DEPLOY_BUCKET-$AWS_REGION/data-lake/$VERSION_CODE --recursive --acl bucket-owner-full-control` including $VERSION_CODE in the end? Because this "detail" is missing in the Readme.

**Comment by shaoliang-jia-dragon** [comment]
I didn't raise this issue. 🤐

**Comment by sardbaba** [comment]
![image](https://user-images.githubusercontent.com/596899/68373176-9f483400-0142-11ea-9a7e-75d599b07f74.png)
