### ISSUE TITLE
READ.ME Wrong Instruction - point 7 

### ISSUE THREAD

**Issue by eAmine** [awslabs/aws-data-lake-solution#28]
The command on point 7 should be: 
aws s3 cp ./dist s3://$DEPLOY_BUCKET/data-lake/$VERSION_CODE --recursive --acl bucket-owner-full-control
Instead Of :
aws s3 cp ./dist s3://$DEPLOY_BUCKET/data-lake/latest --recursive --acl bucket-owner-full-control

**Comment by tomnight** [comment]
Thanks for the feedback we have added your request to our solution backlog items and it will be review it in the next release.

**Comment by georgebearden** [comment]
This issue should have been addressed in the latest commit.
