### ISSUE TITLE
502 error from /prod/cart

### ISSUE THREAD

**Issue by samavedulark** [awslabs/aws-data-lake-solution#32]
Hi,

After enabling SAML, i am getting 502 error from cart service.
I doubt some issue with SAML, as the request is going to elasticserach.
Is there any configuration i need to do after SAML for ElasticSeach and Kibana.

Thanks
Ravi S

**Comment by knihit** [comment]
> Hi,
> 
> After enabling SAML, i am getting 502 error from cart service.
> I doubt some issue with SAML, as the request is going to elasticserach.
> Is there any configuration i need to do after SAML for ElasticSeach and Kibana.
> 
> Thanks
> Ravi S

Hello Ravi,

Do you still see the issue with SAML. Would you be able to provide some any details on the error/ exception from the lambda functions using cloudwatch logs. You should see some errors either in the 'data-lake-cart-service' or in the 'data-lake-authorizer' service.

Thank you

**Comment by samavedulark** [comment]
Hi,

This is solved, we passed the saml as xml rather than redirecting to url.
