### ISSUE TITLE
package ids beginning with dash cant be deleted properly

### ISSUE THREAD

**Issue by jgc234** [awslabs/aws-data-lake-solution#34]
I've run into an issue where package IDs starting with '-' can't be fully deleted.  Elasticsearch barfs which results in the package being deleted, but still searchable in a list.  

from version 2.1.0

```
2019-10-19T10:44:25.506Z	678bd893-cc8c-49dd-b4c1-b6de3c98da68	{ body: { package_id: '-n0RdiWKK' },
resource: '/search/index',
httpMethod: 'DELETE',
headers: ......

path: '/data-lake/_search',
query: { q: 'package_id:-n0RdiWKK' },

displayName: 'BadRequest',
message: '[parse_exception] parse_exception: Encountered " "-" "- "" at line 1, column 11.\nWas expecting one of
```

I assume this could be fixed by specifying a more limited 64-char set for shortid (in  content-package.js:125 ) with shortid.characters(....).. or maybe by escapting/quoting the package_id when building the elasticsearch query (if that's feasible).

If you bulk-delete via the CLI, you'll be left only with packages beginning with '-', so I assume a dash in the middle still works OK.

**Comment by beomseoklee** [comment]
Thanks for your input, and I'm sorry for your inconvenience. We will consider this one in the next release.

**Comment by georgebearden** [comment]
The shortid character set has been updated to remove ‘-‘ in the latest commit. Please let us know if you need additional assistance.
