### ISSUE TITLE
latest npm package for elasticsearch 16.x is not working.

### ISSUE THREAD

**Issue by sardbaba** [awslabs/aws-data-lake-solution#38]
Here: [https://github.com/awslabs/aws-data-lake-solution/blob/fa800dd1b2339184377742a6dc96b1e53f47b6ff/source/api/services/search/package.json#L11](https://github.com/awslabs/aws-data-lake-solution/blob/fa800dd1b2339184377742a6dc96b1e53f47b6ff/source/api/services/search/package.json#L11)

must be changed with something like:

`"elasticsearch": "^15.1.1",`

in order to work with the current code.

Or the current code should be changed in order to work with indexes with more than one type (see also https://discuss.elastic.co/t/unable-to-create-index-with-more-that-1-type-in-6-x/106089 and https://www.elastic.co/blog/index-type-parent-child-join-now-future-in-elasticsearch)

**Comment by ericquinones** [comment]
Thank you for letting us know. We've added this to our backlog and will evaluate in future releases. Please keep an eye on repository for updates.

**Comment by georgebearden** [comment]
To maintain overall consistency of versions across all API services, the elasticsearch npm package is locked down to "^14.2.2" in the latest commit.
