### ISSUE TITLE
Script to build the project

### ISSUE THREAD

**Issue by ruiwanguk** [awslabs/aws-data-lake-solution#4]
Hi,

Is there a script to build the whole project ? 

To give context, we would like to build the whole project and upload it to our S3 bucket which is ready to be deployed. 

Many thanks,
Rui

**Comment by ipolynets** [comment]
Hi @ruiwanguk,

So basically you need to run CloudFormation script. Essentially one click of the button once you have AWS account created: 

Here is the link: https://aws.amazon.com/answers/big-data/data-lake-solution/

Look for the button "Deploy Solution"

**Comment by ruiwanguk** [comment]
Hi @ipolynets,

Thanks. I am aware of the "Deploy Solution" button, however, we are hoping that we could make some changes to the data lake solution, e.g. making some modifications to the cloudformation template, extending lambda functions with additional requirements. To do these, it will require us to build the whole project ourselves instead of using the provided S3 bucket for running the cloudformation script. 

Any comments? 

Best,
Rui

**Comment by ruiwanguk** [comment]
To be more specific about my question, When I am looking the lambda functions, I can see that, in the package.json file, we have grunt, grunt-aws-lambda, grunt-pack and grunt-contrib-clean. However, I don't see any GruntFile in the source code, how was the lambda function built and packaged? 

Rui

**Comment by HayDegha0917** [comment]
+1 on the issue. Also having problems building from scratch.

**Comment by shsenior** [comment]
We will be releasing an update in the next week that will provide build scripts (via bash) for the solution, as well as, support for new regions.

**Comment by ruiwanguk** [comment]
@shsenior thank you. Look forward to the update. 

btw, I also notice that one of unit test for the front-end is currently broken, would this be fixed as well?

**Comment by HayDegha0917** [comment]
Yay! that is awesome. I did get everything to work, but it took longer than necessary.

**Comment by shsenior** [comment]
The latest update v1.3 provides build scripts, unit test and deployment instructions.
