### ISSUE TITLE
Missing API support for /packages

### ISSUE THREAD

**Issue by john-aws** [awslabs/aws-data-lake-solution#5]
Minor bug. The client-side packageFactory.js makes calls to GET /packages but this is not actually supported by the API Gateway code in content-package.js. Existing code does support POST /packages but also needs to support GET /packages. The new code will call _package.getPackages(...)

**Comment by hvital** [comment]
Thanks john!

The [version 2.0 was published](https://aws.amazon.com/about-aws/whats-new/2018/07/the-data-lake-solution-now-transforms-and-analyzes-data/) and listDataPackages references were removed from front-end code. In case you need, list packages is implemented by search service.
