### ISSUE TITLE
Data Lake CI/CD

### ISSUE THREAD

**Issue by ruiwanguk** [awslabs/aws-data-lake-solution#6]
We are currently trying to figure the best way of doing CI/CD with the data lake solution. 

Ideally, we'd like to have a separation of dev and prod environment for the data lake, so we can test changes and add new features. Additionally, it would be really useful if we could deploy different component of the data lake without impacting on the rest of the stack. e.g. deploy changes on the frontend, deploy new lambda function. 

Are the above CI/CD use cases currently supported by the data lake cloudformation templates? Do you have any recommendations on how to archive them?

**Comment by shsenior** [comment]
We leverage AWS CodePipeline to orchestrate our CI/CD for development of the data lake solution. AWS CodeBuild provides the engine in the pipelines to execute our unit tests and updates to the infrastructure. 

Example phases:
Pre-Build: Install dependencies and executing unit tests [./run-unit-tests.sh]
Build: Build and package data lake solution assets [./build-s3-dist.sh]
Post-Build: Update Lambda functions, API definitions, push deployment assets to S3, etc
