### ISSUE TITLE
Failed to call createSearchIndex

### ISSUE THREAD

**Issue by ruiwanguk** [awslabs/aws-data-lake-solution#7]
Hi Team,

We are trying to deploy your data lake solution using cloudformation. However, we are currently getting is "Custom Resource failed to stabilize in expected time" error in Cloudformation when "Custom:LoadLambda" is trying to call createSearchIndex. Any suggestions would be much appreciate. 

Here is the snippet of cloudformation template that causing the problem: 

`DataLakeSearchIndex:
        Type: "Custom::LoadLambda"
        Properties:
            ServiceToken:
                Fn::GetAtt:
                    - "DataLakeHelper"
                    - "Arn"
            Region:
                - Ref: "AWS::Region"
            clusterUrl: !Join ["", ["https://", !GetAtt DataLakeStorageStack.Outputs.EsCluster ]]
            searchIndex: "data-lake"
            customAction: "createSearchIndex"`

Best wishes,
Rui

**Comment by shsenior** [comment]
What region are you trying to deploy the data lake in? There are some regions that do not support all the services required. We will update the readme file with these regions with the next update in the coming week.

**Comment by ruiwanguk** [comment]
Hi @shsenior,

Thank you. I was running the deployment

**Comment by shsenior** [comment]
Should be resolved with the latest update v1.3. Issue was a result of an update to an underlying library. Connection strings to ElasticSearch have been updated to accommodate.
