### ISSUE TITLE
API Access unavailable despite Admin role

### ISSUE THREAD

**Issue by merl-dev** [awslabs/aws-data-lake-solution#9]
I have launched a data lake for testing by launching a script found 
 in http://docs.aws.amazon.com/solutions/latest/data-lake-solution/deployment.html

[Launch Solution](https://console.aws.amazon.com/cloudformation/home?region=us-east-1#/stacks/new?&templateURL=https:%2F%2Fs3.amazonaws.com%2Fsolutions-reference%2Fdata-lake-solution%2Flatest%2Fdata-lake-deploy.template)

Despite being assigned an Admin role, the My Account/Profile/Api Access page indicates that I do not have API access.  What do I need to set in order for this to be enabled?

**Comment by shsenior** [comment]
@merl-dev 

You need to grant your user (whether admin or member role) access to the data lake api. Please review the documentation here [http://docs.awssolutionsbuilder.com/data-lake/admin-guide/working-with-users/#grant-user-api-access] to grant your user access to the API.

**Comment by merl-dev** [comment]
My apologies, go it.
